### PR TITLE
add an initial travis ci yml file

### PR DESCRIPTION
**Pull request by derekstraka**
Signed-off-by: Derek Straka derek@asterius.io

### CODE REVIEW

**Comment by derekstraka** [comment]
The CI builds will be marked as failed for now.  We can either drop the unimplemented tests, allow the builds to fail for now, or ignore the failures in the yml file

**Comment by mathstuf** [comment]
Thanks, but until either GitHub or Travis let me decide *which* of my repos it is allowed write access to, I cannot bring myself to allow it to access my account.

**Comment by mathstuf** [comment]
FWIW, I have [an (ignored) open issue](https://github.com/travis-ci/travis-ci/issues/4871) with Travis about this. I think I've sent a request to Github before about it, but I can't remember. I'll send another.

**Comment by mathstuf** [comment]
I'll keep this open as a reminder to myself.

**Comment by mathstuf** [comment]
Request sent to Github…will see what they say.

**Comment by mathstuf** [comment]
And Cirrus CI configuration has been added to #19.

**Pull request closed without merging**
